# Generated by Django 3.2.7 on 2021-10-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.FloatField(default=0.0)),
                ('right', models.FloatField(default=0.0)),
            ],
        ),
    ]
